# Generated by Django 4.1.1 on 2022-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_email', models.CharField(max_length=50)),
                ('emp_age', models.IntegerField(max_length=3)),
                ('emp_department', models.CharField(max_length=200)),
                ('emp_salary', models.IntegerField(max_length=10)),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_working', models.BooleanField(default=True)),
            ],
        ),
    ]
