# Generated by Django 4.1.1 on 2022-10-25 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_bonus',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_first_name',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_last_name',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_phone',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_salary',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_role',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='emp.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_department',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='emp.department'),
        ),
    ]
