# Generated by Django 4.1.1 on 2022-10-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_department_role_remove_employee_emp_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_name', models.CharField(default=False, max_length=200)),
                ('emp_last_name', models.CharField(default=False, max_length=200)),
                ('emp_age', models.IntegerField(max_length=3)),
                ('emp_salary', models.IntegerField(default=0, max_length=10)),
                ('emp_bonus', models.IntegerField(default=0, max_length=10)),
                ('emp_phone', models.IntegerField(default=0, max_length=10)),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_working', models.BooleanField(default=True)),
                ('emp_department', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='emp.department')),
                ('emp_role', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='emp.role')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
