# Generated by Django 4.1.1 on 2022-10-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_employee1_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='emp_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.department'),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='emp_first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='emp_last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='emp_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
