# Generated by Django 4.1.1 on 2022-10-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_department_name_alter_employee1_emp_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='location',
            new_name='dept_location',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role_name',
        ),
    ]
