# Generated by Django 4.1.1 on 2022-10-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_rename_location_department_dept_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee1',
            name='emp_department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee1',
            name='emp_role',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
